### ISSUE TITLE
Final accuracy result prints "accuracy = 0.00%"

### ISSUE THREAD

**Issue by krishnu9** [krishnu9/ANN-Classifier-for-breast-cancer-prediction#1]
![Screenshot_20190623_015002](https://user-images.githubusercontent.com/39588858/59968570-44c68680-9559-11e9-80e4-a3b0b23452c2.png)
On running "python classifier.py" in the working directory, the model runs and trains successfully but the final accuracy is printed as 0.00%.

**Comment by mikejgray** [comment]
On it!

**Comment by mikejgray** [comment]
Hello @krishnu9, I am unable to replicate this bug in Python 3.7.4. Would you please share what version of Python you're using and what version of each framework you're using? Thank you!

![Screen Shot 2019-10-01 at 12 12 10 PM](https://user-images.githubusercontent.com/30268971/65984169-cc6b3d80-e444-11e9-8b87-d2c7499fdcf0.png)
